import { r0, r1, r2, type GuideBindKey, type GuideRowDef } from './guide-model';

const pct = { unit: 'pct' as const };

/** 재무제표 포괄손익계산서 — IA 3-1. LVL 2가 계정 사전 상한. */
export function incomeStatementRows(): GuideRowDef[] {
  return [
    r0('is-rev', '매출액(수익)', 'revenue'),
    r0('is-cogs', '매출원가', 'cogs'),
    r0('is-gp', '매출총이익', 'gross_profit'),
    r0('is-sga', '판매비와관리비', 'sga', [
      r2('is-sga-hr', '인건비및복리후생비'),
      r2('is-sga-admin', '일반관리비'),
      r2('is-sga-sell', '판매비'),
      r2('is-sga-cogsish', '기타원가성비용'),
      r2('is-sga-other', '기타'),
    ]),
    r0('is-op', '영업이익', 'operating_income'),
    r0('is-op-rpt', '영업이익(발표기준)', 'operating_income'),
    r0('is-fin-inc', '금융수익', undefined, [
      r2('is-fin-inc-int', '이자수익'),
      r2('is-fin-inc-fx', '외환거래이익'),
      r2('is-fin-inc-disp', '금융자산처분이익'),
      r2('is-fin-inc-fv', '금융자산평가이익'),
      r2('is-fin-inc-deriv', '파생상품이익'),
      r2('is-fin-inc-eq', '종속기업,공동지배기업및관계기업(지분법)관련이익'),
      r2('is-fin-inc-other', '기타'),
    ]),
    r0('is-fin-exp', '금융원가', undefined, [
      r2('is-fin-exp-int', '이자비용'),
      r2('is-fin-exp-fx', '외환거래손실'),
      r2('is-fin-exp-disp', '금융자산처분손실'),
      r2('is-fin-exp-fv', '금융자산평가손실'),
      r2('is-fin-exp-deriv', '파생상품손실'),
      r2('is-fin-exp-eq', '종속기업,공동지배기업및관계기업(지분법)관련손실'),
      r2('is-fin-exp-other', '기타'),
    ]),
    r0('is-oi-inc', '기타영업외수익', undefined, [
      r2('is-oi-inc-int', '이자수익'),
      r2('is-oi-inc-div', '배당금수익'),
      r2('is-oi-inc-fx', '외환거래이익'),
      r2('is-oi-inc-disp', '자산처분(폐기)이익'),
      r2('is-oi-inc-eq', '종속기업,공동지배기업및관계기업(지분법)관련이익'),
      r2('is-oi-inc-other', '기타'),
    ]),
    r0('is-oi-exp', '기타영업외비용', undefined, [
      r2('is-oi-exp-int', '이자비용'),
      r2('is-oi-exp-fx', '외환거래손실'),
      r2('is-oi-exp-disp', '자산처분손실'),
      r2('is-oi-exp-eq', '종속기업,공동지배기업및관계기업(지분법)관련손실'),
      r2('is-oi-exp-other', '기타'),
    ]),
    r0('is-eq', '종속기업,공동지배기업및관계기업관련손익', undefined, [
      r2('is-eq-em', '지분법관련손익'),
      r2('is-eq-disp', '관계기업처분손익'),
      r2('is-eq-sub', '종속기업관련손익'),
      r2('is-eq-other', '기타'),
    ]),
    r0('is-ebt', '법인세비용차감전계속사업이익'),
    r0('is-tax', '법인세비용'),
    r0('is-preacq', '종속회사매수일전순손익'),
    r0('is-sold-sub', '처분된종속회사순손익'),
    r0('is-cont', '계속사업이익'),
    r0('is-disc', '중단사업이익'),
    r0('is-ni', '당기순이익', 'net_income', [
      r1('is-ni-ctl', '(지배주주지분)당기순이익'),
      r1('is-ni-nci', '(비지배주주지분)당기순이익'),
    ]),
    r0('is-oci', '기타포괄이익'),
    r0('is-ci', '총포괄이익'),
  ];
}

/** 재무제표 재무상태표 — IA 3-2. */
export function balanceSheetRows(): GuideRowDef[] {
  return [
    r0('bs-assets', '자산총계', 'assets', [
      r1('bs-ca', '유동자산', undefined, [
        r2('bs-ca-inv', '재고자산'),
        r2('bs-ca-bio', '유동생물자산'),
        r2('bs-ca-fvpl', '당기손익-공정가치측정금융자산'),
        r2('bs-ca-fvoc', '기타포괄손익-공정가치측정금융자산'),
        r2('bs-ca-amort-sec', '상각후원가측정유가증권'),
        r2('bs-ca-amort', '상각후원가측정금융자산'),
        r2('bs-ca-st-fin', '단기금융자산'),
        r2('bs-ca-ar', '매출채권및기타채권'),
        r2('bs-ca-tax', '당기법인세자산(선급법인세)'),
        r2('bs-ca-contract', '계약자산'),
        r2('bs-ca-return', '반품(환불)자산'),
        r2('bs-ca-allowance', '배출권'),
        r2('bs-ca-other', '기타유동자산'),
        r2('bs-ca-cash', '현금및현금성자산', 'cash'),
        r2('bs-ca-held', '매각예정비유동자산및처분자산'),
      ]),
      r1('bs-nca', '비유동자산', undefined, [
        r2('bs-nca-ppe', '유형자산'),
        r2('bs-nca-ia', '무형자산'),
        r2('bs-nca-bio', '비유동생물자산'),
        r2('bs-nca-ip', '투자부동산'),
        r2('bs-nca-inv', '투자자산'),
        r2('bs-nca-ar', '장기매출채권및기타채권'),
        r2('bs-nca-dta', '이연법인세자산'),
        r2('bs-nca-tax', '장기당기법인세자산'),
        r2('bs-nca-contract', '계약자산'),
        r2('bs-nca-return', '반품(환불)자산'),
        r2('bs-nca-allowance', '배출권'),
        r2('bs-nca-other', '기타비유동자산'),
      ]),
      r1('bs-fin-a', '기타금융업자산'),
    ]),
    r0('bs-liab', '부채총계', 'liabilities', [
      r1('bs-cl', '유동부채', undefined, [
        r2('bs-cl-st-bond', '단기사채', 'current_bonds'),
        r2('bs-cl-st-bor', '단기차입금', 'st_borrowings'),
        r2('bs-cl-cmlt', '유동성장기부채', 'current_lt_borrowings'),
        r2('bs-cl-fvpl', '당기손익-공정가치측정금융부채'),
        r2('bs-cl-amort', '상각후원가측정금융부채'),
        r2('bs-cl-fin', '유동금융부채'),
        r2('bs-cl-ap', '매입채무및기타채무'),
        r2('bs-cl-emp', '유동종업원급여충당부채'),
        r2('bs-cl-prov', '단기충당부채'),
        r2('bs-cl-tax', '당기법인세부채(미지급법인세)'),
        r2('bs-cl-contract', '계약부채'),
        r2('bs-cl-return', '반품(환불)부채'),
        r2('bs-cl-allowance', '배출부채'),
        r2('bs-cl-other', '기타유동부채'),
        r2('bs-cl-held', '매각예정으로분류된처분자산에포함된부채'),
      ]),
      r1('bs-ncl', '비유동부채', undefined, [
        r2('bs-ncl-bond', '사채', 'bonds'),
        r2('bs-ncl-lt-bor', '장기차입금', 'lt_borrowings'),
        r2('bs-ncl-fvpl', '당기손익-공정가치측정금융부채'),
        r2('bs-ncl-amort', '상각후원가측정금융부채'),
        r2('bs-ncl-fin', '비유동금융부채'),
        r2('bs-ncl-ap', '장기매입채무및기타채무'),
        r2('bs-ncl-emp', '비유동종업원급여충당부채'),
        r2('bs-ncl-prov', '장기충당부채'),
        r2('bs-ncl-dtl', '이연법인세부채'),
        r2('bs-ncl-tax', '장기당기법인세부채(미지급법인세)'),
        r2('bs-ncl-contract', '계약부채'),
        r2('bs-ncl-return', '반품(환불)부채'),
        r2('bs-ncl-allowance', '배출부채'),
        r2('bs-ncl-other', '기타비유동부채'),
      ]),
      r1('bs-fin-l', '기타금융업부채'),
    ]),
    r0('bs-eq', '자본총계', 'equity', [
      r1('bs-eq-ctl', '지배주주지분', undefined, [
        r2('bs-eq-cap', '자본금'),
        r2('bs-eq-hybrid', '신종자본증권'),
        r2('bs-eq-apic', '자본잉여금'),
        r2('bs-eq-other', '기타자본'),
        r2('bs-eq-oci', '기타포괄이익누계액'),
        r2('bs-eq-re', '이익잉여금'),
      ]),
      r1('bs-eq-nci', '비지배주주지분'),
    ]),
  ];
}

/** 재무제표 현금흐름표 — IA 3-3. */
export function cashFlowRows(): GuideRowDef[] {
  return [
    r0('cf-op', '영업활동으로인한현금흐름', 'cf_operating', [
      r1('cf-op-ni', '당기순이익', 'net_income'),
      r1('cf-op-ebt', '법인세비용차감전계속사업이익'),
      r1('cf-op-add', '현금유출이없는비용등가산', undefined, [
        r2('cf-op-add-fin', '금융비용'),
        r2('cf-op-add-int', '이자비용'),
        r2('cf-op-add-div', '배당금지급'),
        r2('cf-op-add-bad', '대손상각비'),
        r2('cf-op-add-bad-o', '기타대손상각비'),
        r2('cf-op-add-sever', '퇴직급여'),
        r2('cf-op-add-da-ppe', '유형자산감가상각비', 'depreciation'),
        r2('cf-op-add-da-dev', '개발비상각'),
        r2('cf-op-add-da-ia', '기타무형자산상각비', 'amortisation'),
        r2('cf-op-add-fx', '외환거래손실'),
        r2('cf-op-add-disp', '금융자산처분손실'),
        r2('cf-op-add-fv', '금융자산평가손실'),
        r2('cf-op-add-inv', '투자자산평가손실'),
        r2('cf-op-add-deriv', '파생상품손실'),
        r2('cf-op-add-em', '지분법관련손실'),
        r2('cf-op-add-sub', '종속기업관련손실'),
        r2('cf-op-add-other', '기타'),
      ]),
      r1('cf-op-sub', '현금유입이없는수익등차감', undefined, [
        r2('cf-op-sub-fin', '금융수익'),
        r2('cf-op-sub-int', '이자수익'),
        r2('cf-op-sub-div', '배당금수익'),
        r2('cf-op-sub-bad', '대손충당금환입액'),
        r2('cf-op-sub-sever', '퇴직급여충당부채환입액'),
        r2('cf-op-sub-fx', '외환거래이익'),
        r2('cf-op-sub-disp', '금융자산처분이익'),
        r2('cf-op-sub-fv', '금융자산평가이익'),
        r2('cf-op-sub-inv', '투자자산평가이익'),
        r2('cf-op-sub-deriv', '파생상품이익'),
        r2('cf-op-sub-em', '지분법관련이익'),
        r2('cf-op-sub-sub', '종속회사관련이익'),
        r2('cf-op-sub-other', '기타'),
      ]),
      r1('cf-op-wc', '영업활동으로인한자산부채변동(운전자본변동)', undefined, [
        r2('cf-op-wc-a', '영업활동자산의감소'),
        r2('cf-op-wc-l', '영업활동부채의증가'),
        r2('cf-op-wc-gov', '정부보조금등의변동'),
        r2('cf-op-wc-other', '기타운전자본의변동'),
      ]),
      r1('cf-op-cfo', '*영업에서창출된현금흐름'),
      r1('cf-op-int', '이자수입(지급)'),
      r1('cf-op-div', '배당금수입(지급)'),
      r1('cf-op-tax', '법인세환입(납부)'),
      r1('cf-op-disc', '중단사업관련현금흐름'),
    ]),
    r0('cf-inv', '투자활동으로인한현금흐름', 'cf_investing', [
      r1('cf-inv-in', '투자활동현금유입액', undefined, [
        r2('cf-inv-in-inv', '투자자산의감소'),
        r2('cf-inv-in-pen', '퇴직급여,보험,연금자산의감소'),
        r2('cf-inv-in-ppe', '유형자산의감소'),
        r2('cf-inv-in-ia', '무형자산의감소'),
        r2('cf-inv-in-bio', '생물자산의감소'),
        r2('cf-inv-in-ip', '투자부동산의감소'),
        r2('cf-inv-in-other', '기타투자활동으로인한현금유입액'),
      ]),
      r1('cf-inv-out', '투자활동현금유출액', undefined, [
        r2('cf-inv-out-inv', '투자자산의증가'),
        r2('cf-inv-out-pen', '퇴직급여,보험,연금자산의증가'),
        r2('cf-inv-out-ppe', '유형자산의증가'),
        r2('cf-inv-out-ia', '무형자산의증가'),
        r2('cf-inv-out-bio', '생물자산증가'),
        r2('cf-inv-out-ip', '투자부동산의증가'),
        r2('cf-inv-out-other', '기타투자활동으로인한현금유출액'),
      ]),
      r1('cf-inv-int', '이자수입(지급)'),
      r1('cf-inv-div', '배당금수입(지급)'),
      r1('cf-inv-tax', '법인세환입(납부)'),
      r1('cf-inv-disc', '중단사업관련현금흐름'),
    ]),
    r0('cf-fin', '재무활동으로인한현금흐름', 'cf_financing', [
      r1('cf-fin-in', '재무활동현금유입액', undefined, [
        r2('cf-fin-in-cl', '유동부채의증가'),
        r2('cf-fin-in-ncl', '비유동부채의증가'),
        r2('cf-fin-in-ol', '기타부채의증가'),
        r2('cf-fin-in-eq', '자본의증가'),
        r2('cf-fin-in-other', '기타재무활동으로인한현금유입액'),
      ]),
      r1('cf-fin-out', '재무활동현금유출액', undefined, [
        r2('cf-fin-out-cl', '유동부채의감소'),
        r2('cf-fin-out-ncl', '비유동부채의감소'),
        r2('cf-fin-out-ol', '기타부채의감소'),
        r2('cf-fin-out-eq', '자본의감소'),
        r2('cf-fin-out-other', '기타재무활동으로인한현금유출액'),
      ]),
      r1('cf-fin-int', '이자수입(지급)'),
      r1('cf-fin-div', '배당금수입(지급)'),
      r1('cf-fin-tax', '법인세환입(납부)'),
      r1('cf-fin-disc', '중단사업관련현금흐름'),
      r1('cf-fin-other', '영업투자재무활동기타현금흐름'),
      r1('cf-fin-scope', '연결범위변동으로인한현금의증가'),
      r1('cf-fin-fx', '환율변동효과'),
    ]),
    r0('cf-delta', '현금및현금성자산의증가'),
    r0('cf-open', '기초현금및현금성자산'),
    r0('cf-close', '기말현금및현금성자산', 'cash'),
  ];
}

/** Snapshot Financial Highlight — IA 1. 들여쓰기만, 재무제표보다 얕다. */
export function snapshotHighlightRows(): GuideRowDef[] {
  return [
    r0('hl-rev', '매출액', 'revenue'),
    r0('hl-op', '영업이익', 'operating_income'),
    r0('hl-op-rpt', '영업이익(발표기준)', 'operating_income'),
    r0('hl-ni', '당기순이익', 'net_income', [
      r1('hl-ni-ctl', '당기순이익(지배)'),
      r1('hl-ni-nci', '당기순이익(비지배)'),
    ]),
    r0('hl-assets', '자산총계', 'assets'),
    r0('hl-liab', '부채총계', 'liabilities'),
    r0('hl-eq', '자본총계', 'equity', [
      r1('hl-eq-ctl', '자본총계(지배)'),
      r1('hl-eq-nci', '자본총계(비지배)'),
    ]),
    r0('hl-cap', '자본금'),
    r0('hl-debt', '부채비율', 'debt_ratio_pct', undefined, pct),
    r0('hl-reserve', '유보율', undefined, undefined, pct),
    r0('hl-opm', '영업이익률', 'opm_pct', undefined, pct),
    r0('hl-npm', '순이익률(지배)', 'npm_pct', undefined, pct),
    r0('hl-roa', 'ROA', undefined, undefined, pct),
    r0('hl-roe', 'ROE', 'roe_pct', undefined, pct),
    r0('hl-eps', 'EPS'),
    r0('hl-bps', 'BPS'),
    r0('hl-dps', '현금DPS'),
    r0('hl-per', 'PER'),
    r0('hl-pbr', 'PBR'),
    r0('hl-shares', '발행주식수(보통주)', undefined, undefined, { unit: 'shares' }),
    r0('hl-div', '현금배당수익률', undefined, undefined, pct),
  ];
}

function ratio(
  id: string,
  label: string,
  formula: string,
  bind: GuideBindKey | undefined,
  left: GuideRowDef,
  right: GuideRowDef,
): GuideRowDef {
  return r1(id, label, bind, [left, right], { unit: 'pct', formula });
}

/** 재무비율 연간 — IA 4. + 는 산식 구성항. */
export function ratioAnnualRows(): GuideRowDef[] {
  return [
    r0('ra-stable', '안정성비율', undefined, [
      ratio(
        'ra-current',
        '유동비율',
        '(유동자산 / 유동부채) * 100',
        undefined,
        r2('ra-current-a', '유동자산'),
        r2('ra-current-l', '유동부채'),
      ),
      ratio(
        'ra-quick',
        '당좌비율',
        '(당좌자산 / 유동부채) * 100',
        undefined,
        r2('ra-quick-a', '당좌자산'),
        r2('ra-quick-l', '유동부채'),
      ),
      ratio(
        'ra-debt',
        '부채비율',
        '(부채총계 / 자본총계) * 100',
        'debt_ratio_pct',
        r2('ra-debt-l', '부채총계', 'liabilities'),
        r2('ra-debt-e', '자본총계', 'equity'),
      ),
      ratio(
        'ra-reserve',
        '유보율',
        '(유보액 / 자본금) * 100',
        undefined,
        r2('ra-reserve-a', '유보액', undefined, { formula: '자본잉여금 + 이익잉여금' }),
        r2('ra-reserve-c', '자본금'),
      ),
      ratio(
        'ra-nd',
        '순부채비율',
        '(순부채 / 자본총계) * 100',
        'net_debt_ratio',
        r2('ra-nd-d', '순부채', 'net_debt', {
          formula: '총차입부채 − (현금및현금성자산 + 단기금융자산)',
        }),
        r2('ra-nd-e', '자본총계', 'equity'),
      ),
      ratio(
        'ra-icr',
        '이자보상배율',
        '영업이익 / 이자비용(비영업)',
        undefined,
        r2('ra-icr-op', '영업이익', 'operating_income'),
        r2('ra-icr-int', '이자비용'),
      ),
      ratio(
        'ra-eq',
        '자기자본비율',
        '(자본총계 / 자산총계) * 100',
        'equity_ratio',
        r2('ra-eq-e', '자본총계', 'equity'),
        r2('ra-eq-a', '자산총계', 'assets'),
      ),
    ]),
    r0('ra-growth', '성장성비율', undefined, [
      ratio(
        'ra-g-rev',
        '매출액증가율',
        '((매출액 / 매출액(-1Y)) − 1) * 100',
        'yoy:revenue',
        r2('ra-g-rev-0', '매출액', 'revenue'),
        r2('ra-g-rev-1', '매출액 (-1Y)'),
      ),
      ratio(
        'ra-g-sga',
        '판매비와관리비증가율',
        '((판매비와관리비 / 판매비와관리비(-1Y)) − 1) * 100',
        'yoy:sga',
        r2('ra-g-sga-0', '판매비와관리비', 'sga'),
        r2('ra-g-sga-1', '판매비와관리비 (-1Y)'),
      ),
      ratio(
        'ra-g-op',
        '영업이익증가율',
        '((영업이익 / 영업이익(-1Y)) − 1) * 100',
        'yoy:operating_income',
        r2('ra-g-op-0', '영업이익', 'operating_income'),
        r2('ra-g-op-1', '영업이익 (-1Y)'),
      ),
      ratio(
        'ra-g-ebitda',
        'EBITDA증가율',
        '((EBITDA / EBITDA(-1Y)) − 1) * 100',
        'yoy:ebitda',
        r2('ra-g-ebitda-0', 'EBITDA', 'ebitda', { formula: '영업이익 + 유무형자산상각비' }),
        r2('ra-g-ebitda-1', 'EBITDA (-1Y)'),
      ),
      ratio(
        'ra-g-eps',
        'EPS증가율',
        '수정EPS / 수정EPS(-1Y)',
        undefined,
        r2('ra-g-eps-0', 'EPS', undefined, { formula: '당기순이익(지배) / 수정평균발행주식수' }),
        r2('ra-g-eps-1', 'EPS (-1Y)'),
      ),
    ]),
    r0('ra-profit', '수익성비율', undefined, [
      ratio(
        'ra-gpm',
        '매출총이익률',
        '매출총이익 / 매출액',
        'gpm_pct',
        r2('ra-gpm-gp', '매출총이익', 'gross_profit'),
        r2('ra-gpm-rev', '매출액', 'revenue'),
      ),
      ratio(
        'ra-ebt',
        '세전계속사업이익률',
        '세전계속사업이익 / 매출액',
        undefined,
        r2('ra-ebt-i', '세전계속사업이익'),
        r2('ra-ebt-rev', '매출액', 'revenue'),
      ),
      ratio(
        'ra-opm',
        '영업이익률',
        '영업이익 / 매출액',
        'opm_pct',
        r2('ra-opm-op', '영업이익', 'operating_income'),
        r2('ra-opm-rev', '매출액', 'revenue'),
      ),
      ratio(
        'ra-ebitda-m',
        'EBITDA마진율',
        'EBITDA / 매출액',
        undefined,
        r2('ra-ebitda-m-e', 'EBITDA', 'ebitda'),
        r2('ra-ebitda-m-rev', '매출액', 'revenue'),
      ),
      ratio(
        'ra-roa',
        'ROA',
        '당기순이익(직전4분기) / 자산총계(평균)',
        undefined,
        r2('ra-roa-ni', '당기순이익 (직전4분기)', 'net_income'),
        r2('ra-roa-a', '자산총계 (평균)', 'assets'),
      ),
      ratio(
        'ra-roe',
        'ROE',
        '당기순이익(지배,직전4분기) / 자본총계(지배,평균)',
        'roe_pct',
        r2('ra-roe-ni', '당기순이익(지배) (직전4분기)', 'net_income'),
        r2('ra-roe-e', '자본총계(지배) (평균)', 'equity'),
      ),
      ratio(
        'ra-roic',
        'ROIC',
        'NOPLAT(직전4분기) / IC(평균)',
        undefined,
        r2('ra-roic-n', 'NOPLAT (직전4분기)', undefined, { formula: '세후영업이익' }),
        r2('ra-roic-ic', 'IC', undefined, { formula: '영업투하자본(평균)' }),
      ),
    ]),
    r0('ra-activity', '활동성비율', undefined, [
      ratio(
        'ra-at',
        '총자산회전율',
        '매출액(직전4분기) / 자산총계(평균)',
        undefined,
        r2('ra-at-rev', '매출액 (직전4분기)', 'revenue'),
        r2('ra-at-a', '자산총계 (평균)', 'assets'),
      ),
      ratio(
        'ra-lt',
        '총부채회전율',
        '매출액(직전4분기) / 부채총계(평균)',
        undefined,
        r2('ra-lt-rev', '매출액 (직전4분기)', 'revenue'),
        r2('ra-lt-l', '부채총계 (평균)', 'liabilities'),
      ),
      ratio(
        'ra-et',
        '자기자본회전율',
        '매출액(직전4분기) / 자본총계(평균)',
        undefined,
        r2('ra-et-rev', '매출액 (직전4분기)', 'revenue'),
        r2('ra-et-e', '자본총계 (평균)', 'equity'),
      ),
      ratio(
        'ra-nwc',
        '순운전자본회전율',
        '매출액(직전4분기) / 순운전자본(평균)',
        undefined,
        r2('ra-nwc-rev', '매출액 (직전4분기)', 'revenue'),
        r2('ra-nwc-w', '순운전자본 (평균)'),
      ),
    ]),
  ];
}

/** 재무비율 3개월 — 안정성·활동성 없음. */
export function ratioQuarterRows(): GuideRowDef[] {
  return [
    r0('rq-growth', '성장성비율', undefined, [
      ratio(
        'rq-g-rev',
        '매출액증가율',
        '((매출액 / 매출액(-1Y)) − 1) * 100',
        'yoy:revenue',
        r2('rq-g-rev-0', '매출액', 'revenue'),
        r2('rq-g-rev-1', '매출액 (-1Y)'),
      ),
      ratio(
        'rq-g-op',
        '영업이익증가율',
        '((영업이익 / 영업이익(-1Y)) − 1) * 100',
        'yoy:operating_income',
        r2('rq-g-op-0', '영업이익', 'operating_income'),
        r2('rq-g-op-1', '영업이익 (-1Y)'),
      ),
      ratio(
        'rq-g-ebitda',
        'EBITDA증가율',
        '((EBITDA / EBITDA(-1Y)) − 1) * 100',
        'yoy:ebitda',
        r2('rq-g-ebitda-0', 'EBITDA', 'ebitda'),
        r2('rq-g-ebitda-1', 'EBITDA (-1Y)'),
      ),
      ratio(
        'rq-g-eps',
        'EPS증가율',
        '수정EPS / 수정EPS(-1Y)',
        undefined,
        r2('rq-g-eps-0', 'EPS'),
        r2('rq-g-eps-1', 'EPS (-1Y)'),
      ),
    ]),
    r0('rq-profit', '수익성비율', undefined, [
      ratio(
        'rq-ebt',
        '세전계속사업이익률',
        '세전계속사업이익 / 매출액',
        undefined,
        r2('rq-ebt-i', '세전계속사업이익'),
        r2('rq-ebt-rev', '매출액', 'revenue'),
      ),
      ratio(
        'rq-opm',
        '영업이익률',
        '영업이익 / 매출액',
        'opm_pct',
        r2('rq-opm-op', '영업이익', 'operating_income'),
        r2('rq-opm-rev', '매출액', 'revenue'),
      ),
      ratio(
        'rq-ebitda-m',
        'EBITDA마진율',
        'EBITDA / 매출액',
        undefined,
        r2('rq-ebitda-m-e', 'EBITDA', 'ebitda'),
        r2('rq-ebitda-m-rev', '매출액', 'revenue'),
      ),
    ]),
  ];
}

/** 투자지표 기업가치 — IA 5. */
export function investValueRows(): GuideRowDef[] {
  return [
    r0('iv-ps', 'Per Share', undefined, [
      r1(
        'iv-eps',
        'EPS (원)',
        undefined,
        [r2('iv-eps-ni', '당기순이익(지배)', 'net_income'), r2('iv-eps-sh', '수정평균발행주식수 (주)', undefined, { unit: 'shares' })],
        { formula: '당기순이익(지배) / 수정평균발행주식수' },
      ),
      r1(
        'iv-ebitdaps',
        'EBITDAPS (원)',
        undefined,
        [
          r2('iv-ebitdaps-e', 'EBITDA', 'ebitda', { formula: '영업이익 + 유무형자산상각비' }),
          r2('iv-ebitdaps-sh', '수정평균발행주식수 (주)', undefined, { unit: 'shares' }),
        ],
        { formula: 'EBITDA / 수정평균발행주식수' },
      ),
      r1(
        'iv-cfps',
        'CFPS (원)',
        undefined,
        [
          r2('iv-cfps-cf', '현금흐름', undefined, { formula: '당기순이익 + 감가상각비' }),
          r2('iv-cfps-sh', '수정평균발행주식수 (주)', undefined, { unit: 'shares' }),
        ],
        { formula: '현금흐름 / 수정평균발행주식수' },
      ),
      r1(
        'iv-sps',
        'SPS (원)',
        undefined,
        [r2('iv-sps-rev', '매출액', 'revenue'), r2('iv-sps-sh', '수정평균발행주식수 (주)', undefined, { unit: 'shares' })],
        { formula: '매출액 / 수정평균발행주식수' },
      ),
      r1(
        'iv-bps',
        'BPS (원)',
        undefined,
        [
          r2('iv-bps-eq', '자본총계(지배)', 'equity'),
          r2('iv-bps-sh', '수정기말발행주식수(자사주차감) (주)', undefined, { unit: 'shares' }),
        ],
        { formula: '자본총계(지배) / 수정기말발행주식수(자사주차감)' },
      ),
    ]),
    r0('iv-div', 'Dividends', undefined, [
      r1(
        'iv-dps-c',
        '수정DPS(보통주,현금) (원)',
        undefined,
        [r2('iv-dps-c-raw', 'DPS(보통주,현금)'), r2('iv-dps-c-adj', '무상조정수정계수 (보통주)')],
        { formula: 'DPS(보통주,현금) × 무상조정수정계수' },
      ),
      r1('iv-dps-p', '수정DPS(우선주,현금) (원)', undefined, [
        r2('iv-dps-p-raw', 'DPS(우선주,현금)'),
        r2('iv-dps-p-adj', '무상조정수정계수 (우선주)'),
      ]),
      r1(
        'iv-payout',
        '현금배당성향 (%)',
        undefined,
        [r2('iv-payout-div', '배당금(현금)'), r2('iv-payout-ni', '당기순이익(지배)', 'net_income')],
        { unit: 'pct', formula: '배당금(현금) / 당기순이익(지배)' },
      ),
    ]),
    r0('iv-mult', 'Multiples', undefined, [
      r1(
        'iv-per',
        'PER',
        undefined,
        [r2('iv-per-p', '보통주수정주가(기말)'), r2('iv-per-eps', 'EPS')],
        { formula: '보통주수정주가(기말) / 수정EPS(직전4분기)' },
      ),
      r1(
        'iv-pcr',
        'PCR',
        undefined,
        [r2('iv-pcr-p', '보통주수정주가(기말)'), r2('iv-pcr-cfps', 'CFPS')],
        { formula: '보통주수정주가(기말) / 수정CFPS' },
      ),
      r1(
        'iv-psr',
        'PSR',
        undefined,
        [r2('iv-psr-p', '보통주수정주가(기말)'), r2('iv-psr-sps', 'SPS')],
        { formula: '보통주수정주가(기말) / 수정SPS' },
      ),
      r1(
        'iv-pbr',
        'PBR',
        undefined,
        [r2('iv-pbr-p', '보통주수정주가(기말)'), r2('iv-pbr-bps', 'BPS')],
        { formula: '보통주수정주가(기말) / 수정BPS' },
      ),
      r1(
        'iv-evs',
        'EV/Sales',
        undefined,
        [r2('iv-evs-ev', 'EV', undefined, { formula: '시가총액 + 순부채' }), r2('iv-evs-rev', '매출액', 'revenue')],
        { formula: 'EV / 매출액(직전4분기)' },
      ),
      r1('iv-eve', 'EV/EBITDA', undefined, [r2('iv-eve-ev', 'EV'), r2('iv-eve-e', 'EBITDA', 'ebitda')]),
    ]),
    r0('iv-fcf', 'FCF', undefined, [
      r1('iv-fcf-cfo', '영업활동으로인한현금흐름', 'cf_operating'),
      r1('iv-fcf-capex', 'CAPEX', undefined, undefined, { formula: '(C/F)유형자산의증가' }),
      r1('iv-fcf-fcf', 'FCF', undefined, undefined, { formula: '영업활동으로인한현금흐름 − CAPEX' }),
    ]),
  ];
}

export const MULTIFACTOR_AXES = [
  '베타',
  '배당성',
  '수익건전성',
  '성장성',
  '기업투자',
  '거시경제 민감도',
  '모멘텀',
  '단기 Return',
  '기업규모',
  '거래도',
  '밸류',
  '변동성',
] as const;
